CREATE TABLE alert (
id SERIAL PRIMARY KEY,
optlock TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
message VARCHAR(255),
startdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
strap_id VARCHAR(255)
);
